version: "3"

services:

  postgres:
    image: postgres:15.3
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - postgres

  shortener:
    build: .
    depends_on:
      - postgres
    ports:
      - "9000:8000"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

  
  